project_id = "hojiwryocskwvpczaltn"

[functions.fetch-leaderboard]
verify_jwt = false

[functions.upload-leaderboard]
verify_jwt = false

[functions.leaderboard-webhook]
verify_jwt = false

[functions.evaluate-badges]
verify_jwt = false

[functions.evaluate-warnings]
verify_jwt = false