-- ============================================================
-- Add store_name column and populate from Excel data
-- ============================================================

ALTER TABLE company_monitoring
  ADD COLUMN IF NOT EXISTS store_name TEXT;

-- Update store names based on company_code
UPDATE company_monitoring SET store_name = 'HU Baja' WHERE company_code = 'H002';
UPDATE company_monitoring SET store_name = 'HU Balassagyarmat' WHERE company_code = 'H003';
UPDATE company_monitoring SET store_name = 'HU Békéscsaba' WHERE company_code = 'H005';
UPDATE company_monitoring SET store_name = 'HU Berettyóújfalu' WHERE company_code = 'H006';
UPDATE company_monitoring SET store_name = 'HU Csepel' WHERE company_code = 'H007';
UPDATE company_monitoring SET store_name = 'HU Debrecen' WHERE company_code = 'H008';
UPDATE company_monitoring SET store_name = 'HU Dunaharaszti' WHERE company_code = 'H010';
UPDATE company_monitoring SET store_name = 'HU Dunakeszi' WHERE company_code = 'H011';
UPDATE company_monitoring SET store_name = 'HU Dunaújváros' WHERE company_code = 'H012';
UPDATE company_monitoring SET store_name = 'HU Eger (Gyöngyös)' WHERE company_code = 'H013';
UPDATE company_monitoring SET store_name = 'HU Érd' WHERE company_code = 'H014';
UPDATE company_monitoring SET store_name = 'HU Gödöllő' WHERE company_code = 'H015';
UPDATE company_monitoring SET store_name = 'HU Gyomaendrőd' WHERE company_code = 'H016';
UPDATE company_monitoring SET store_name = 'HU Hódmezővásárhely' WHERE company_code = 'H019';
UPDATE company_monitoring SET store_name = 'HU Hűvösvölgy' WHERE company_code = 'H020';
UPDATE company_monitoring SET store_name = 'HU Kapuvár' WHERE company_code = 'H023';
UPDATE company_monitoring SET store_name = 'HU Karcag' WHERE company_code = 'H024';
UPDATE company_monitoring SET store_name = 'HU Kazincbarcika' WHERE company_code = 'H025';
UPDATE company_monitoring SET store_name = 'HU Keszthely' WHERE company_code = 'H027';
UPDATE company_monitoring SET store_name = 'HU Kiskunfélegyháza' WHERE company_code = 'H029';
UPDATE company_monitoring SET store_name = 'HU Kiskunlacháza' WHERE company_code = 'H031';
UPDATE company_monitoring SET store_name = 'HU Kispest' WHERE company_code = 'H032';
UPDATE company_monitoring SET store_name = 'HU Körmend' WHERE company_code = 'H035';
UPDATE company_monitoring SET store_name = 'HU Kunhegyes' WHERE company_code = 'H036';
UPDATE company_monitoring SET store_name = 'HU Lenti' WHERE company_code = 'H037';
UPDATE company_monitoring SET store_name = 'HU Mátészalka' WHERE company_code = 'H039';
UPDATE company_monitoring SET store_name = 'HU Miskolc' WHERE company_code = 'H040';
UPDATE company_monitoring SET store_name = 'HU Mohács' WHERE company_code = 'H041';
UPDATE company_monitoring SET store_name = 'HU Nagykanizsa' WHERE company_code = 'H044';
UPDATE company_monitoring SET store_name = 'HU Nagykáta (Cegléd, Jászberény)' WHERE company_code = 'H045';
UPDATE company_monitoring SET store_name = 'HU Nyíregyháza' WHERE company_code = 'H047';
UPDATE company_monitoring SET store_name = 'HU Óbuda' WHERE company_code = 'H048';
UPDATE company_monitoring SET store_name = 'HU Ózd' WHERE company_code = 'H050';
UPDATE company_monitoring SET store_name = 'HU Paks' WHERE company_code = 'H051';
UPDATE company_monitoring SET store_name = 'HU Pápa' WHERE company_code = 'H052';
UPDATE company_monitoring SET store_name = 'HU Pécs' WHERE company_code = 'H054';
UPDATE company_monitoring SET store_name = 'HU Piliscsaba' WHERE company_code = 'H055';
UPDATE company_monitoring SET store_name = 'HU Rákoskeresztúr' WHERE company_code = 'H056';
UPDATE company_monitoring SET store_name = 'HU Salgótarján' WHERE company_code = 'H057';
UPDATE company_monitoring SET store_name = 'HU Sárospatak' WHERE company_code = 'H058';
UPDATE company_monitoring SET store_name = 'HU Siófok' WHERE company_code = 'H061';
UPDATE company_monitoring SET store_name = 'HU Sopron' WHERE company_code = 'H062';
UPDATE company_monitoring SET store_name = 'HU Sümeg' WHERE company_code = 'H063';
UPDATE company_monitoring SET store_name = 'HU Szeged' WHERE company_code = 'H065';
UPDATE company_monitoring SET store_name = 'HU Székesfehérvár' WHERE company_code = 'H066';
UPDATE company_monitoring SET store_name = 'HU Szentes' WHERE company_code = 'H069';
UPDATE company_monitoring SET store_name = 'HU Tatabánya' WHERE company_code = 'H071';
UPDATE company_monitoring SET store_name = 'HU Újpalota, Soroksár, Vecsés' WHERE company_code = 'H074';
UPDATE company_monitoring SET store_name = 'HU Újpest' WHERE company_code = 'H075';
UPDATE company_monitoring SET store_name = 'HU Vác' WHERE company_code = 'H076';
UPDATE company_monitoring SET store_name = 'HU Várpalota, Balatonlelle' WHERE company_code = 'H077';
UPDATE company_monitoring SET store_name = 'HU Veresegyház, Esztergom' WHERE company_code = 'H078';
UPDATE company_monitoring SET store_name = 'HU Veszprém' WHERE company_code = 'H079';
UPDATE company_monitoring SET store_name = 'HU Zugló' WHERE company_code = 'H081';
UPDATE company_monitoring SET store_name = 'HU Kiskőrös' WHERE company_code = 'H086';
UPDATE company_monitoring SET store_name = 'HU Mezőtúr' WHERE company_code = 'H089';
UPDATE company_monitoring SET store_name = 'HU Szombathely' WHERE company_code = 'H090';
UPDATE company_monitoring SET store_name = 'HU Hatvan' WHERE company_code = 'H092';
UPDATE company_monitoring SET store_name = 'HU Kalocsa' WHERE company_code = 'H093';
UPDATE company_monitoring SET store_name = 'HU Dombóvár' WHERE company_code = 'H095';
UPDATE company_monitoring SET store_name = 'HU Szekszárd' WHERE company_code = 'H097';
UPDATE company_monitoring SET store_name = 'HU Komárom' WHERE company_code = 'H099';
UPDATE company_monitoring SET store_name = 'HU Barcs' WHERE company_code = 'H100';
UPDATE company_monitoring SET store_name = 'HU Bonyhád' WHERE company_code = 'H101';
UPDATE company_monitoring SET store_name = 'HU Tapolca' WHERE company_code = 'H102';
UPDATE company_monitoring SET store_name = 'HU Kisvárda' WHERE company_code = 'H103';
UPDATE company_monitoring SET store_name = 'HU Nagykőrös, Törökszentmiklós, Kecskemét, Szolnok' WHERE company_code = 'H105';
UPDATE company_monitoring SET store_name = 'HU Kaposvár' WHERE company_code = 'H106';
UPDATE company_monitoring SET store_name = 'HU Komló' WHERE company_code = 'H108';
UPDATE company_monitoring SET store_name = 'HU Szarvas' WHERE company_code = 'H109';
UPDATE company_monitoring SET store_name = 'HU Kiskunhalas' WHERE company_code = 'H110';
UPDATE company_monitoring SET store_name = 'HU Mezőkövesd' WHERE company_code = 'H112';
UPDATE company_monitoring SET store_name = 'HU Hajdúszoboszló' WHERE company_code = 'H113';
UPDATE company_monitoring SET store_name = 'HU Győr' WHERE company_code = 'H114';
UPDATE company_monitoring SET store_name = 'HU Mosonmagyaróvár' WHERE company_code = 'H115';
UPDATE company_monitoring SET store_name = 'HU Angyalföld, Monor, Csömör' WHERE company_code = 'H116';
UPDATE company_monitoring SET store_name = 'HU Zalaegerszeg' WHERE company_code = 'H117';
UPDATE company_monitoring SET store_name = 'HU Ajka' WHERE company_code = 'H118';
UPDATE company_monitoring SET store_name = 'HU Hajdúböszörmény' WHERE company_code = 'H119';
UPDATE company_monitoring SET store_name = 'HU Tiszaújváros' WHERE company_code = 'H120';
UPDATE company_monitoring SET store_name = 'HU Szentendre' WHERE company_code = 'H121';
UPDATE company_monitoring SET store_name = 'HU Dabas' WHERE company_code = 'H122';
UPDATE company_monitoring SET store_name = 'HU Balatonfüred' WHERE company_code = 'H123';
UPDATE company_monitoring SET store_name = 'HU Újbuda' WHERE company_code = 'H124';
