-- ============================================================
-- Seed franchise companies from Excel
-- These are inserted with company_code + name only.
-- Tax numbers will be resolved via RapidSearch2 on first check-all.
-- ============================================================

-- First, make tax_number nullable (it was NOT NULL originally)
-- Tax numbers will be resolved via RapidSearch2 on first check-all.
ALTER TABLE company_monitoring ALTER COLUMN tax_number DROP NOT NULL;

-- Also drop the UNIQUE constraint on tax_number temporarily so companies
-- without tax numbers (NULL) don't conflict
-- (PostgreSQL allows multiple NULLs in unique columns by default, so this is fine)

INSERT INTO company_monitoring (company_code, company_name, is_active)
VALUES
  ('H000', 'Diego Kereskedelmi és Szolgáltató Kft.', true),
  ('H002', 'Diego-Pencz Kft.', true),
  ('H003', 'Juszt-Bau Kft.', true),
  ('H005', 'Szép-Lak Duó Kft.', true),
  ('H006', 'Silvaniaimpex Kft.', true),
  ('H007', 'DIEGO-Csepel  Ackermann Market Kft.', true),
  ('H008', 'Diego Debrecen Kft.', true),
  ('H010', 'DIEGO Laminált Kft.', true),
  ('H011', 'Diego Lakás Design Kft.', true),
  ('H012', 'Diego Dunaújváros Kft.', true),
  ('H013', 'Diego Eger Kft.', true),
  ('H014', 'BO-NA Szőnyeg Kft.', true),
  ('H015', 'Diego-Radnai Kft.', true),
  ('H016', 'Gyoma Holding Kft.', true),
  ('H019', 'HÓD-PADLÓ KFT.', true),
  ('H020', 'Diego Hűvösvölgy Kft.', true),
  ('H023', 'Scala GM Kft.', true),
  ('H024', 'Softyhome Kft.', true),
  ('H025', 'Diego Barcika Kereskedelmi Kft.', true),
  ('H027', 'Padlón Járunk Kft.', true),
  ('H029', 'B&B Festékcenter Kft.', true),
  ('H031', 'Laguna-Gold Kft.', true),
  ('H032', 'TIMEWRITER Ker és Szolg Kft.', true),
  ('H035', 'GO-RI KERESKEDELMI KFT.', true),
  ('H036', 'Rabné Gégény Erzsébet e. v.', true),
  ('H037', 'Pantha kereskedelmi Kft.', true),
  ('H039', 'Diego 24 Kft.', true),
  ('H040', 'Diego Szőnyegüzletek M. Kft.', true),
  ('H041', 'Diego-Mohács Kft.', true),
  ('H044', 'Jobylak Kereskedelmi Szolgáltató Kft.', true),
  ('H045', 'C-VISO BT.', true),
  ('H047', 'Diego 24 Kft.', true),
  ('H048', 'Diego Óbuda Kft.', true),
  ('H050', 'BRD SERVICES Kft.', true),
  ('H051', 'Reich Trade Ker. Szolg. Bt.', true),
  ('H052', 'Pap Zoltán E.V.', true),
  ('H054', 'DIEGO SOPHIANAE Kft.', true),
  ('H055', 'Diego Óbuda Kft.', true),
  ('H056', 'Stílus 17 Kft.', true),
  ('H057', 'Mátra Stúdió Plusz Kft.', true),
  ('H058', 'DIEGO-SÁROSPATAK KFT.', true),
  ('H061', 'Polimix Ker.Kft.', true),
  ('H062', 'Diego Sopron Bt.', true),
  ('H063', 'Szépítőudvar Kft.', true),
  ('H065', 'PROVAL Kft.', true),
  ('H066', 'D-Fehérvár Kft.', true),
  ('H069', 'Molnár Farkas Róbert', true),
  ('H071', 'FLOORATTO KFT.', true),
  ('H074', 'Sztárpadló Kereskedelmi Kft.', true),
  ('H075', 'Diego Újpest Kft.', true),
  ('H076', 'Papjó Kft.', true),
  ('H077', 'Bodrogi-Sárfi Kft.', true),
  ('H078', 'HELVID KERESKEDELMI ÉS SZOLGÁLTATÓ KFT.', true),
  ('H079', 'Diego Veszprém Kft.', true),
  ('H081', 'M&W Bt./DIEGO ZUGLÓ ÁRUHÁZ', true),
  ('H086', 'Kőrös Padló Kft.', true),
  ('H089', 'Actor Informatika és Nyomda Kft.', true),
  ('H090', 'Store724 Kft.', true),
  ('H092', 'DIEGO-DOBOS 60 KFT.', true),
  ('H093', 'Kalo-Padló Kft', true),
  ('H095', 'Dávid Márk egyéni vállalkozó', true),
  ('H097', 'DIEGO Szekszárd Kft.', true),
  ('H099', 'Interierklinika Kereskedelmi és Szolgált', true),
  ('H100', 'Aragon-Invest Befektetési Kft.', true),
  ('H101', 'BEDO-GROUP Kft.', true),
  ('H102', 'Vida-Kersner Anita E.V.', true),
  ('H103', 'DIEGO 24 Kft.', true),
  ('H105', 'Olifan Kft.', true),
  ('H106', 'D-Kapospadló Kft.', true),
  ('H108', 'Diego Komló Kft.', true),
  ('H109', 'COOP SZOLNOK KERESKEDELMI ZRT.', true),
  ('H110', 'Diego Halas Kft.', true),
  ('H112', 'Jónás Árpád és társa Kft.', true),
  ('H113', 'Lakvaszép Kft.', true),
  ('H114', 'DIEGO Arrabona Kft.', true),
  ('H115', 'DIEGO Arrabona Kft.', true),
  ('H116', 'Liguria Mercante Kft.', true),
  ('H117', 'DIEGO Zalaegerszeg Kft.', true),
  ('H118', 'Bajáti Kft.', true),
  ('H119', 'Sipos és Szegedi Kft.', true),
  ('H120', 'Tisza Diego Kft.', true),
  ('H121', 'Diego Óbuda Kft.', true),
  ('H122', 'Bi-EGO Kft.', true),
  ('H123', 'Sterbikduo Kft.', true),
  ('H124', 'Dominó 2001 Kft', true)
ON CONFLICT DO NOTHING;
